dist: bionic
os: linux
language: shell

env:
  global:
    - IMAGE_NAME=orbnedon/sonarr
git:
  depth: false

services:
  - docker

before_script:
# Find a better solution to get latest version
  - export SONARR_VERSION="$(curl -s https://github.com/Sonarr/Sonarr/releases | grep "/Sonarr/Sonarr/releases/tag/" | head -n1 | sed -e 's/<a href="\/Sonarr\/Sonarr\/releases\/tag\/v//g' | sed -e 's/">//g' | tr -d '[:space:]')"
  - echo "$REGISTRY_PASS" | docker login docker.io -u "$REGISTRY_USER" --password-stdin
  - docker pull $IMAGE_NAME || true
script:
  - docker build --build-arg SONARR_VERSION=${SONARR_VERSION} --pull --cache-from $IMAGE_NAME --tag $IMAGE_NAME .
  - docker run --name sonarr -d -p 8989:8989 ${IMAGE_NAME}
  - sleep 20
  - docker logs sonarr
  - curl --retry 20 --retry-connrefused --retry-delay 3 -s http://localhost:8989 >/dev/null 2>&1
  - docker stop sonarr
  - docker rm -f sonarr
  - docker tag $IMAGE_NAME:latest ${IMAGE_NAME}:v${SONARR_VERSION}
  - docker images

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
